name: bug-tracker

services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=3333
    ports:
      - "3333:3333"
    networks:
      - my-network

  frontend:
    build:
      context: .
      dockerfile: ./apps/bug-tracker-frontend/Dockerfile
    environment:
      - VITE_API_PATH=/api
    ports:
      - "80:80"
    depends_on:
      - api
    links:
     - api
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
